# Generated by Django 3.2.7 on 2021-10-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='stocked',
            field=models.BooleanField(default=True),
        ),
    ]
