# Generated by Django 3.2.7 on 2021-10-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
