# Generated by Django 3.2.7 on 2021-10-19 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_order_orderedmenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderNum',
        ),
    ]
