# Generated by Django 3.2.7 on 2021-10-19 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_order_ordernum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paymentState',
        ),
    ]
